name: 'teste'

on:
  push:
    branches:
      - 'master'

jobs:
  copy-files:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@v4'

      - name: configuring ssh key
        run: 'echo "${{ secrets.DEPLOY_SERVER_KEY }}" >> ~/.ssh/id_rsa
          && chmod 400 ~/.ssh/id_rsa'

      - name: 'sending files to remote machine'
        run: 'scp \
          -i ~/.ssh/id_rsa \
          -o StrictHostKeyChecking=no \
          src package.json package-lock.json \
          ${{ secrets.DEPLOY_SERVER_USER }}@${{ secrets.DEPLOY_SERVER_HOST }}:/opt/applications/test'
