name: 'Teste'

on:
  push:
    branches:
      - 'master'

jobs:
  copy-files:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Copy files'
        run: 'scp \
          -i ${{ secrets.DEPLOY_SERVER_KEY }} \
          -o StrictHostKeyChecking=no \
          src package.json package-lock.json \
          ${{ secrets.DEPLOY_SERVER_USER }}@${{ secrets.DEPLOY_SERVER_HOST }}:/opt/applications/test'
